packages:
  - packages/*
  - apps/*
  - plugins/*
allowBuilds:
  '@google/genai': true
  '@swc/core': true
  better-sqlite3: true
  core-js: false
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  msw: true
  node-pty: true
  protobufjs: true
  sharp: true
  simple-git-hooks: false
minimumReleaseAgeExclude:
  - '@hijarvis/core@0.1.0'
  - '@anthropic-ai/claude-agent-sdk-darwin-arm64@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-darwin-x64@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64-musl@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-linux-x64-musl@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-linux-x64@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-win32-arm64@0.3.205'
  - '@anthropic-ai/claude-agent-sdk-win32-x64@0.3.205'
  - '@anthropic-ai/claude-agent-sdk@0.3.205'
  - '@arcships/light-ocr-darwin-arm64@0.1.0'
  - '@arcships/light-ocr-darwin-x64@0.1.0'
  - '@arcships/light-ocr-linux-x64-gnu@0.1.0'
  - '@arcships/light-ocr-model-ppocrv6-small@0.1.0'
  - '@arcships/light-ocr-win32-x64@0.1.0'
  - '@arcships/light-ocr@0.1.0'
patchedDependencies:
  '@elysiajs/node@1.4.5': patches/@elysiajs__node@1.4.5.patch
