import type { ChatViewProps } from './ChatView'

export const chatFixture: ChatViewProps = {
  session: {
    id: 'session-1',
    execution: { kind: 'local' },
    parentSessionId: null,
    sideContextSource: null,
    workspaceId: 'workspace-1',
    title: 'Build Cradle Mobile',
    origin: 'work',
    providerTargetId: 'provider-1',
    agentId: null,
    modelId: 'gpt-5.6',
    thinkingEffort: 'high',
    linkedIssueId: null,
    sessionGroupId: null,
    runtimeKind: 'codex',
    status: 'streaming',
    pinned: 0,
    archivedAt: null,
    lastReadAt: null,
    createdAt: 1_750_000_000,
    updatedAt: 1_750_000_100,
    latestUserMessageAt: 1_750_000_100,
    latestAssistantMessageAt: null,
    unread: false,
    isIsolated: true,
    worktreeId: 'worktree-1',
    worktreeBranch: 'cradle/wt/mobile',
    worktreePath: '/tmp/mobile',
    worktreeHealth: 'ok',
    pendingWorktreeId: null,
    isolationBoundaryRequired: false,
  },
  messages: [],
  onCancel: () => {},
  onSend: () => {},
}
