const CRADLE_PR_FOOTER = 'Generated by [Cradle](https://cradle.wibus.ren)'

/** Append Cradle attribution to PR body; skip if already present. */
export function withCradlePullRequestFooter(body: string | undefined): string {
  const trimmed = body?.trim() ?? ''
  if (trimmed.includes(CRADLE_PR_FOOTER) || trimmed.includes('https://cradle.wibus.ren')) {
    return trimmed
  }
  if (!trimmed) {
    return CRADLE_PR_FOOTER
  }
  return `${trimmed}\n\n---\n\n${CRADLE_PR_FOOTER}`
}
