import { describe, expect, it } from 'vitest'

import { parseGitHubOwnerRepo } from './github-remote'
import { withCradlePullRequestFooter } from './pr-body'

describe('parseGitHubOwnerRepo', () => {
  it('parses HTTPS GitHub URLs', () => {
    expect(parseGitHubOwnerRepo('https://github.com/acme/widgets.git')).toEqual({
      owner: 'acme',
      repo: 'widgets',
    })
  })

  it('parses SSH GitHub URLs', () => {
    expect(parseGitHubOwnerRepo('git@github.com:acme/widgets.git')).toEqual({
      owner: 'acme',
      repo: 'widgets',
    })
  })

  it('rejects non-GitHub remotes', () => {
    expect(parseGitHubOwnerRepo('https://gitlab.com/acme/widgets.git')).toBeNull()
  })
})

describe('withCradlePullRequestFooter', () => {
  it('appends footer after body', () => {
    expect(withCradlePullRequestFooter('## Summary\n- fix')).toBe(
      '## Summary\n- fix\n\n---\n\nGenerated by [Cradle](https://cradle.wibus.ren)',
    )
  })

  it('uses footer alone when body is empty', () => {
    expect(withCradlePullRequestFooter(undefined)).toBe(
      'Generated by [Cradle](https://cradle.wibus.ren)',
    )
  })

  it('does not duplicate footer', () => {
    const body = 'x\n\nGenerated by [Cradle](https://cradle.wibus.ren)'
    expect(withCradlePullRequestFooter(body)).toBe(body)
  })
})
