/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as DevtoolRouteImport } from './routes/devtool'
import { Route as AwaitsRouteImport } from './routes/awaits'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces/$workspaceId'
import { Route as SettingsSectionRouteImport } from './routes/settings/$section'
import { Route as KanbanBoardIdRouteImport } from './routes/kanban/$boardId'
import { Route as ChatNewRouteImport } from './routes/chat/new'
import { Route as ChatSessionIdRouteImport } from './routes/chat/$sessionId'
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from './routes/workspaces/$workspaceId/index'
import { Route as WorkspacesWorkspaceIdDiffsRouteImport } from './routes/workspaces/$workspaceId/diffs'
import { Route as PluginsRouteSegmentLocalIdRouteImport } from './routes/plugins/$routeSegment/$localId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolRoute = DevtoolRouteImport.update({
  id: '/devtool',
  path: '/devtool',
  getParentRoute: () => rootRouteImport,
} as any)
const AwaitsRoute = AwaitsRouteImport.update({
  id: '/awaits',
  path: '/awaits',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanBoardIdRoute = KanbanBoardIdRouteImport.update({
  id: '/kanban/$boardId',
  path: '/kanban/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatNewRoute = ChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const WorkspacesWorkspaceIdDiffsRoute =
  WorkspacesWorkspaceIdDiffsRouteImport.update({
    id: '/diffs',
    path: '/diffs',
    getParentRoute: () => WorkspacesWorkspaceIdRoute,
  } as any)
const PluginsRouteSegmentLocalIdRoute =
  PluginsRouteSegmentLocalIdRouteImport.update({
    id: '/plugins/$routeSegment/$localId',
    path: '/plugins/$routeSegment/$localId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/awaits': typeof AwaitsRoute
  '/devtool': typeof DevtoolRoute
  '/diff': typeof DiffRoute
  '/onboarding': typeof OnboardingRoute
  '/usage': typeof UsageRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/new': typeof ChatNewRoute
  '/kanban/$boardId': typeof KanbanBoardIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$routeSegment/$localId': typeof PluginsRouteSegmentLocalIdRoute
  '/workspaces/$workspaceId/diffs': typeof WorkspacesWorkspaceIdDiffsRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/awaits': typeof AwaitsRoute
  '/devtool': typeof DevtoolRoute
  '/diff': typeof DiffRoute
  '/onboarding': typeof OnboardingRoute
  '/usage': typeof UsageRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/new': typeof ChatNewRoute
  '/kanban/$boardId': typeof KanbanBoardIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$routeSegment/$localId': typeof PluginsRouteSegmentLocalIdRoute
  '/workspaces/$workspaceId/diffs': typeof WorkspacesWorkspaceIdDiffsRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/awaits': typeof AwaitsRoute
  '/devtool': typeof DevtoolRoute
  '/diff': typeof DiffRoute
  '/onboarding': typeof OnboardingRoute
  '/usage': typeof UsageRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/new': typeof ChatNewRoute
  '/kanban/$boardId': typeof KanbanBoardIdRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRouteWithChildren
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$routeSegment/$localId': typeof PluginsRouteSegmentLocalIdRoute
  '/workspaces/$workspaceId/diffs': typeof WorkspacesWorkspaceIdDiffsRoute
  '/workspaces/$workspaceId/': typeof WorkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/awaits'
    | '/devtool'
    | '/diff'
    | '/onboarding'
    | '/usage'
    | '/chat/$sessionId'
    | '/chat/new'
    | '/kanban/$boardId'
    | '/settings/$section'
    | '/workspaces/$workspaceId'
    | '/plugins/'
    | '/plugins/$routeSegment/$localId'
    | '/workspaces/$workspaceId/diffs'
    | '/workspaces/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/awaits'
    | '/devtool'
    | '/diff'
    | '/onboarding'
    | '/usage'
    | '/chat/$sessionId'
    | '/chat/new'
    | '/kanban/$boardId'
    | '/settings/$section'
    | '/plugins'
    | '/plugins/$routeSegment/$localId'
    | '/workspaces/$workspaceId/diffs'
    | '/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/awaits'
    | '/devtool'
    | '/diff'
    | '/onboarding'
    | '/usage'
    | '/chat/$sessionId'
    | '/chat/new'
    | '/kanban/$boardId'
    | '/settings/$section'
    | '/workspaces/$workspaceId'
    | '/plugins/'
    | '/plugins/$routeSegment/$localId'
    | '/workspaces/$workspaceId/diffs'
    | '/workspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  AwaitsRoute: typeof AwaitsRoute
  DevtoolRoute: typeof DevtoolRoute
  DiffRoute: typeof DiffRoute
  OnboardingRoute: typeof OnboardingRoute
  UsageRoute: typeof UsageRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  ChatNewRoute: typeof ChatNewRoute
  KanbanBoardIdRoute: typeof KanbanBoardIdRoute
  SettingsSectionRoute: typeof SettingsSectionRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRouteWithChildren
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsRouteSegmentLocalIdRoute: typeof PluginsRouteSegmentLocalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtool': {
      id: '/devtool'
      path: '/devtool'
      fullPath: '/devtool'
      preLoaderRoute: typeof DevtoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awaits': {
      id: '/awaits'
      path: '/awaits'
      fullPath: '/awaits'
      preLoaderRoute: typeof AwaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban/$boardId': {
      id: '/kanban/$boardId'
      path: '/kanban/$boardId'
      fullPath: '/kanban/$boardId'
      preLoaderRoute: typeof KanbanBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/new': {
      id: '/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ChatNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId/': {
      id: '/workspaces/$workspaceId/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/workspaces/$workspaceId/diffs': {
      id: '/workspaces/$workspaceId/diffs'
      path: '/diffs'
      fullPath: '/workspaces/$workspaceId/diffs'
      preLoaderRoute: typeof WorkspacesWorkspaceIdDiffsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRoute
    }
    '/plugins/$routeSegment/$localId': {
      id: '/plugins/$routeSegment/$localId'
      path: '/plugins/$routeSegment/$localId'
      fullPath: '/plugins/$routeSegment/$localId'
      preLoaderRoute: typeof PluginsRouteSegmentLocalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspacesWorkspaceIdRouteChildren {
  WorkspacesWorkspaceIdDiffsRoute: typeof WorkspacesWorkspaceIdDiffsRoute
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
}

const WorkspacesWorkspaceIdRouteChildren: WorkspacesWorkspaceIdRouteChildren = {
  WorkspacesWorkspaceIdDiffsRoute: WorkspacesWorkspaceIdDiffsRoute,
  WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
}

const WorkspacesWorkspaceIdRouteWithChildren =
  WorkspacesWorkspaceIdRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  AwaitsRoute: AwaitsRoute,
  DevtoolRoute: DevtoolRoute,
  DiffRoute: DiffRoute,
  OnboardingRoute: OnboardingRoute,
  UsageRoute: UsageRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  ChatNewRoute: ChatNewRoute,
  KanbanBoardIdRoute: KanbanBoardIdRoute,
  SettingsSectionRoute: SettingsSectionRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRouteWithChildren,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsRouteSegmentLocalIdRoute: PluginsRouteSegmentLocalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
