import type { WorkspaceViewProps } from './workspace-view-contract'

export const workspaceFixture: WorkspaceViewProps = {
  workspace: {
    id: 'workspace-1',
    name: 'Cradle',
    locator: { nodeId: 'local', path: '/Users/demo/dev/cradle', kind: 'project' },
    gitIdentity: { branch: 'main' },
    identifier: 'cradle',
    multiFolder: false,
    availability: 'available',
    pinned: 1,
    createdAt: 1_750_000_000,
    updatedAt: 1_750_000_000,
  },
  workspaces: [
    {
      id: 'workspace-1',
      name: 'Cradle',
      locator: { nodeId: 'local', path: '/Users/demo/dev/cradle', kind: 'project' },
      gitIdentity: { branch: 'main' },
      identifier: 'cradle',
      multiFolder: false,
      availability: 'available',
      pinned: 1,
      createdAt: 1_750_000_000,
      updatedAt: 1_750_000_000,
    },
  ],
  sessions: [{
    id: 'session-1',
    execution: { kind: 'local' },
    parentSessionId: null,
    sideContextSource: null,
    workspaceId: 'workspace-1',
    title: 'Polish the Mobile experience',
    origin: 'mobile',
    providerTargetId: null,
    agentId: null,
    modelId: 'gpt-5.6',
    thinkingEffort: 'high',
    linkedIssueId: null,
    sessionGroupId: null,
    runtimeKind: 'codex',
    status: 'idle',
    pinned: 1,
    archivedAt: null,
    lastReadAt: 1_750_000_000,
    createdAt: 1_750_000_000,
    updatedAt: 1_750_000_100,
    activityAt: 1_750_000_100,
    latestUserMessageAt: 1_750_000_050,
    latestAssistantMessageAt: 1_750_000_100,
    unread: true,
    isIsolated: false,
    worktreeId: null,
    worktreeBranch: null,
    worktreePath: null,
    worktreeHealth: null,
    pendingWorktreeId: null,
    isolationBoundaryRequired: false,
  }],
  works: [],
  files: [
    { type: 'directory', name: 'apps', path: 'apps' },
    { type: 'file', name: 'README.md', path: 'README.md' },
  ],
  onCreate: () => {},
  onBrowseFiles: () => {},
  onOpenFile: () => {},
  onOpenSession: () => {},
  onOpenWork: () => {},
  onOpenWorkInfo: () => {},
  onSetSessionPinned: () => {},
}
