import type { WorkDetailViewProps } from './WorkDetailView'

export const workDetailFixture: WorkDetailViewProps = {
  detail: {
    work: {
      id: 'work-1',
      title: 'Improve mobile review flow',
      objective: 'Make Work status and handoff details available away from the desktop.',
      linkedIssueId: null,
      handoffTitle: 'Improve mobile review flow',
      handoffSummary: 'Adds a focused mobile handoff workflow.',
      handoffTestPlan: 'Verified with mobile type checking.',
      preparedAt: 1_750_000_000_000,
      lastSubmittedAt: null,
      closedAt: null,
      archivedAt: null,
      createdAt: 1_750_000_000_000,
      updatedAt: 1_750_000_100_000,
    },
    primaryThread: {
      id: 'session-1',
      execution: { kind: 'local' },
      parentSessionId: null,
      sideContextSource: null,
      workspaceId: 'workspace-1',
      title: 'Improve mobile review flow',
      origin: 'work',
      providerTargetId: null,
      agentId: 'codex',
      modelId: 'gpt-5',
      thinkingEffort: 'high',
      linkedIssueId: null,
      sessionGroupId: null,
      runtimeKind: 'codex',
      status: 'idle',
      pinned: 0,
      archivedAt: null,
      lastReadAt: 1_750_000_100_000,
      createdAt: 1_750_000_000_000,
      updatedAt: 1_750_000_100_000,
      latestUserMessageAt: 1_750_000_000_000,
      latestAssistantMessageAt: 1_750_000_100_000,
      unread: false,
      isIsolated: true,
      worktreeId: 'worktree-1',
      worktreeBranch: 'feat/mobile-review',
      worktreePath: '/workspace/.worktrees/mobile-review',
      worktreeHealth: 'ok',
      pendingWorktreeId: null,
      isolationBoundaryRequired: false,
    },
    execution: {
      isIsolated: true,
      worktreeId: 'worktree-1',
      worktreeBranch: 'feat/mobile-review',
      worktreePath: '/workspace/.worktrees/mobile-review',
      worktreeHealth: 'ok',
      pendingWorktreeId: null,
      isolationBoundaryRequired: false,
    },
    readiness: {
      isolated: true,
      clean: true,
      branch: 'feat/mobile-review',
      baseRef: 'main',
      commitsAhead: 2,
      changedFiles: 6,
    },
    pullRequest: null,
    activity: 'idle',
  },
  onOpenPullRequest: () => {},
  onPrepare: () => {},
  onRefresh: () => {},
  onSubmit: () => {},
}
