import type { WorkDetailViewProps } from './work-detail-view-contract'

export const workDetailFixture: WorkDetailViewProps = {
  detail: {
    activity: 'idle',
    execution: {
      isIsolated: true,
      isolationBoundaryRequired: true,
      pendingWorktreeId: null,
      worktreeBranch: 'cradle/wt/mobile-controller',
      worktreeHealth: 'ok',
      worktreeId: 'worktree-1',
      worktreePath: '/Users/demo/dev/cradle-mobile-controller',
    },
    primaryThread: {
      agentId: null,
      archivedAt: null,
      activityAt: 1_750_000_100,
      createdAt: 1_750_000_000,
      execution: { kind: 'local' },
      id: 'session-1',
      isIsolated: true,
      isolationBoundaryRequired: true,
      lastReadAt: 1_750_000_000,
      latestAssistantMessageAt: 1_750_000_100,
      latestUserMessageAt: 1_750_000_050,
      linkedIssueId: null,
      modelId: null,
      origin: 'cradle',
      parentSessionId: null,
      pendingWorktreeId: null,
      pinned: 0,
      providerTargetId: null,
      runtimeKind: 'codex',
      sessionGroupId: null,
      sideContextSource: null,
      status: 'idle',
      thinkingEffort: null,
      title: 'Improve Mobile controller',
      unread: false,
      updatedAt: 1_750_000_100,
      workspaceId: 'workspace-1',
      worktreeBranch: 'cradle/wt/mobile-controller',
      worktreeHealth: 'ok',
      worktreeId: 'worktree-1',
      worktreePath: '/Users/demo/dev/cradle-mobile-controller',
    },
    pullRequest: null,
    readiness: {
      baseRef: 'main',
      branch: 'cradle/wt/mobile-controller',
      changedFiles: 4,
      clean: true,
      commitsAhead: 2,
      isolated: true,
    },
    work: {
      archivedAt: null,
      closedAt: null,
      createdAt: 1_750_000_000,
      handoffSummary: 'Adds reliable Mobile controls.',
      handoffTestPlan: 'Mobile TypeScript and targeted ESLint.',
      handoffTitle: 'feat(mobile): improve controller',
      id: 'work-1',
      lastSubmittedAt: null,
      linkedIssueId: null,
      objective: 'Improve the remote Mobile controller workflow.',
      preparedAt: 1_750_000_100,
      title: 'Improve Mobile controller',
      updatedAt: 1_750_000_100,
    },
  },
  onOpenPullRequest: () => {},
  onPrepare: async () => {},
  onSubmit: async () => {},
}
