import type { PullRequestDetailViewProps } from './PullRequestDetailView'
import type { PullRequestListViewProps } from './PullRequestListView'

const pullRequest = {
  owner: 'cradle',
  repo: 'cradle',
  number: 42,
  url: 'https://github.com/cradle/cradle/pull/42',
  title: 'feat(mobile): add focused mobile controller',
  isDraft: true,
  state: 'open' as const,
  merged: false,
  headRef: 'cradle/wt/mobile',
  baseRef: 'main',
  headSha: 'abc123',
  createdAt: 1_750_000_000,
  updatedAt: 1_750_000_100,
  additions: 420,
  deletions: 12,
  checksState: 'pending' as const,
}

export const pullRequestListFixture: PullRequestListViewProps = {
  authored: [pullRequest],
  reviewing: [],
  login: 'demo',
  onNavigate: () => {},
  onOpen: () => {},
  onOpenUsage: () => {},
}

export const pullRequestDetailFixture: PullRequestDetailViewProps = {
  detail: {
    pullRequest: {
      ...pullRequest,
      author: {
        login: 'demo',
        avatarUrl: 'https://avatars.githubusercontent.com/u/1?v=4',
        url: 'https://github.com/demo',
      },
      body: 'Adds a focused mobile controller for checking Work and pull requests away from the desktop.',
      changedFiles: 8,
      commits: 3,
      comments: 2,
      reviewComments: 1,
      mergeable: true,
      mergeableState: 'clean',
      createdAtIso: '2026-07-20T10:00:00.000Z',
      updatedAtIso: '2026-07-20T11:00:00.000Z',
      closedAtIso: null,
      mergedAtIso: null,
      reviewers: [],
      assignees: [],
      labels: [{ name: 'mobile', color: '0e8a16' }],
      checks: [{
        id: 'check-1',
        name: 'Mobile typecheck',
        status: 'completed',
        conclusion: 'success',
        url: 'https://github.com/cradle/cradle/actions/runs/1',
      }],
      allowedMergeMethods: ['squash'],
      mergeBlockers: [],
      canMerge: true,
    },
    timeline: [{
      id: 'comment-1',
      kind: 'comment',
      author: { login: 'reviewer', avatarUrl: null, url: 'https://github.com/reviewer' },
      body: 'The mobile flow is ready for another pass.',
      state: null,
      createdAt: '2026-07-20T10:30:00.000Z',
      url: 'https://github.com/cradle/cradle/pull/42#issuecomment-1',
    }],
    files: [{
      sha: 'abc123',
      filename: 'apps/mobile/src/features/projects/ProjectsView.tsx',
      previousFilename: null,
      status: 'modified',
      additions: 24,
      deletions: 4,
      changes: 28,
      patch: '@@ -1,2 +1,4 @@',
      blobUrl: 'https://github.com/cradle/cradle/blob/abc123/apps/mobile/src/features/projects/ProjectsView.tsx',
      rawUrl: 'https://github.com/cradle/cradle/raw/abc123/apps/mobile/src/features/projects/ProjectsView.tsx',
    }],
  },
  onComment: () => {},
  onOpenExternal: () => {},
  onRefresh: () => {},
  onReview: () => {},
}
