export const BROWSER_NATIVE_SURFACE_OCCLUSION_ATTRIBUTE = 'data-browser-native-surface-occlusion'

export const BROWSER_NATIVE_SURFACE_OCCLUSION_SELECTOR
  = `[${BROWSER_NATIVE_SURFACE_OCCLUSION_ATTRIBUTE}="true"]`

export const BROWSER_NATIVE_SURFACE_OCCLUSION_PROPS = {
  [BROWSER_NATIVE_SURFACE_OCCLUSION_ATTRIBUTE]: 'true',
} as const
