import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs'],
  target: 'node22',
  sourcemap: true,
  clean: true,
  outExtensions: () => ({ js: '.cjs' }),
  banner: {
    js: '#!/usr/bin/env node',
  },
  deps: {
    alwaysBundle: [
      '@clack/prompts',
      /^@cradle\/plugin-sdk(?:\/.*)?$/,
      'commander',
      'marked',
      'picocolors',
      'string-width',
      'table',
      'zod',
    ],
    onlyBundle: [
      '@clack/core',
      '@clack/prompts',
      'ajv',
      'ansi-regex',
      'ansi-styles',
      'astral-regex',
      'color-convert',
      'color-name',
      'commander',
      'emoji-regex',
      'fast-deep-equal',
      'fast-string-truncated-width',
      'fast-string-width',
      'fast-wrap-ansi',
      'get-east-asian-width',
      'is-fullwidth-code-point',
      'lodash.truncate',
      'marked',
      'picocolors',
      'sisteransi',
      'slice-ansi',
      'string-width',
      'strip-ansi',
      'table',
      'zod',
    ],
  },
  dts: false,
})
